### ISSUE TITLE
【输入文章链接后】显示获取失败

### ISSUE THREAD

**Issue by edmund-zhao** [mwx2006/SFacg-Book#1]
输入：http://book.sfacg.com/Novel/196814
http://book.sfacg.com/Novel/196814/MainIndex/
http://book.sfacg.com/Novel/196814/306076/2620551/
都报错

**Comment by xiankanmengluohua** [comment]
萌新想知道怎么输入链接( •́ .̫ •̀ )

**Comment by edmund-zhao** [comment]
https://t.me/sfnovel
不需要文章的全部链接，要的是小说目录的bookid

—— Edmund Zhao

在 2021年2月14日，下午9:19，xiankanmengluohua <notifications@github.com> 写道：

﻿
EXTERNAL EMAIL:

萌新想知道怎么输入链接( •́ .̫ •̀ )

**Comment by xiankanmengluohua** [comment]
首先，感谢大佬告诉我链接是小说目录的bookid，（我并不知道要用小说目录的bookid，如果没有告诉我，估计后面还有得懵B）还有我想知道链接是在哪里输入的，我直接打开sfacg-Book的黑色界面，输入链接后无法运行（我是用Shift+F10来运行的，但是这样子没有反应）

**Comment by edmund-zhao** [comment]
> 首先，感谢大佬告诉我链接是小说目录的bookid，（我并不知道要用小说目录的bookid，如果没有告诉我，估计后面还有得懵B）还有我想知道链接是在哪里输入的，我直接打开sfacg-Book的黑色界面，输入链接后无法运行（我是用Shift+F10来运行的，但是这样子没有反应）

用terminal 来运行，powershell 或者 cmd都可以

**Comment by edmund-zhao** [comment]
> 首先，感谢大佬告诉我链接是小说目录的bookid，（我并不知道要用小说目录的bookid，如果没有告诉我，估计后面还有得懵B）还有我想知道链接是在哪里输入的，我直接打开sfacg-Book的黑色界面，输入链接后无法运行（我是用Shift+F10来运行的，但是这样子没有反应）

还有，可以考虑用我的项目，不过由于某些原因，源代码放tg群里了

**Comment by xiankanmengluohua** [comment]
tg群组是https://t.me/sfnovel这个吗？呃，我打不开

**Comment by edmund-zhao** [comment]
需要代理的🥸，算是门槛吧

—— Edmund Zhao

在 2021年2月15日，下午8:29，xiankanmengluohua <notifications@github.com> 写道：

﻿
EXTERNAL EMAIL:

tg群组是https://t.me/sfnovel这个吗？呃，我打不开<https://t.me/sfnovel%E8%BF%99%E4%B8%AA%E5%90%97%EF%BC%9F%E5%91%83%EF%BC%8C%E6%88%91%E6%89%93%E4%B8%8D%E5%BC%80>

**Comment by xiankanmengluohua** [comment]
![微信图片_20210219221946](https://user-images.githubusercontent.com/79047145/108518169-3965c880-7303-11eb-82b3-537ab8ae8a69.png)
![微信图片_20210219221955](https://user-images.githubusercontent.com/79047145/108518175-3b2f8c00-7303-11eb-91ab-68cf936be934.png)
就是是我进行到这一步但是不知道在哪里输入小说目录的bookid

**Comment by xiankanmengluohua** [comment]
然后我又下载了一个pycharm运行找到的代码然后发现好像
![微信图片_20210219224218](https://user-images.githubusercontent.com/79047145/108518690-cc066780-7303-11eb-9911-0a1542ea1d81.png)
运行后的结果和直接打开SFacg-Book-2.0.tar差不多

**Comment by xiankanmengluohua** [comment]
如果能发一下你如何使用使用该爬虫的录屏，我将感激不尽

**Comment by wusiyunfeng2B** [comment]
Traceback (most recent call last):
  File "sf.py", line 252, in <module>
  File "sf.py", line 44, in sf
UnboundLocalError: local variable 'ret' referenced before assignment
[13980] Failed to execute script sf
输入id之后，得到这个报错。windows版。请问哪里出错了？

**Comment by edmund-zhao** [comment]
SF改版了，基本上半个月内没有更新的脚本都无法使用了

在 2021年3月23日，上午10:34，wusiyunfeng2B ***@***.***> 写道：

﻿
EXTERNAL EMAIL:

Traceback (most recent call last):
File "sf.py", line 252, in
File "sf.py", line 44, in sf
UnboundLocalError: local variable 'ret' referenced before assignment
[13980] Failed to execute script sf
输入id之后，得到这个报错。windows版。请问哪里出错了？
